model:
  NAME: TANet
  global_encoder_args:
    NAME: PointNet2Encoder
    in_channels: 28 # feature channels: C dims
    width: null
    layers: 3
    use_res: False
    strides: [2, 4, 1]
    mlps: [[[64, 64, 128]],
          [[128, 128, 256]],
          [[256, 512, 1024]]]
    radius: [0.2, 0.4, null]
    num_samples: [32, 64, null]
    sample_method: fps
    aggr_args:
      NAME: 'convpool'
      feature_type: 'dp_fj'
      anisotropic: False
      reduction: 'max'
    group_args:
      NAME: 'ballquery'
      use_xyz: True
      normalize_dp: False
    conv_args: 
      order: conv-norm-act
    act_args:
      act: 'relu'
    norm_args:
      norm: 'bn'
  local_encoder_args:
    NAME: PointNet2Encoder
    in_channels: 3
    width: null
    layers: 3
    use_res: False
    strides: [2, 4, 1]
    mlps: [[[32, 32, 64]],
          [[64, 64, 128]],
          [[128, 256, 512]]]
    radius: [0.2, 0.4, null]
    num_samples: [32, 64, null]
    sample_method: fps
    aggr_args:
      NAME: 'convpool'
      feature_type: 'dp_fj'
      anisotropic: False
      reduction: 'max'
    group_args:
      NAME: 'ballquery'
      use_xyz: True
      normalize_dp: False
    conv_args: 
      order: conv-norm-act
    act_args:
      act: 'relu'
    norm_args:
      norm: 'bn'
  pose_regressor:
    NAME: MLPs
    Xi_dim: 32
    fpm_embedding_dims: 512
    mlps: [[1568, 1024], #Xi_dim + global + local
          [1024, 256],
          [256, 6]]
    activators: [relu, relu, tanh]
    dropouts: [0.3, 0.3, 0.]
  feature_propagation_module:
    NAME: FPM
    K_iter: 3
    rnn:
      NAME: GRUs
      T_step: 3
      input_size: 512
      hidden_size: 512
